apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cronjobmanagers.mygroup.example.com
spec:
  group: mygroup.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                globalSuspend:
                  type: boolean
                  description: A single switch to suspend all managed cronjobs.
                jobs:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: The name of the cronjob to create.
                      namespace:
                        type: string
                        description: The target namespace to deploy the cronjob into.
                      schedule:
                        type: string
                        description: The cron schedule (e.g., "*/5 * * * *").
                      jobTemplate:
                        type: object
                        description: The full JobTemplateSpec, same as in a regular CronJob.
                        x-kubernetes-preserve-unknown-fields: true # Allows the full v1.JobTemplateSpec
                    required:
                      - name
                      - namespace
                      - schedule
                      - jobTemplate
              required:
                - jobs
  scope: Namespaced # Our CronJobManager resource will live in a specific namespace
  names:
    plural: cronjobmanagers
    singular: cronjobmanager
    kind: CronJobManager
    shortNames:
      - cjm
